/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package PRESENTACIONES;

import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JPanel;


import DATO.DAOusuario;
import ENTIDAD.Eusuario;
import NEGOCIO.Nusuario;



public class Frm_Menu extends javax.swing.JFrame {

   private Eusuario ingresar;

   
    public Frm_Menu() {
        initComponents();
     this.setLocationRelativeTo(null);
     
     
    
        
   
        addMouseHoverEffect(panelcliente);
        addMouseHoverEffect(paneldestajero);
        addMouseHoverEffect(panelmodelo);
        addMouseHoverEffect(panelproducto);
        addMouseHoverEffect(panelusuario);
        addMouseHoverEffect(panelreporte);
        addMouseHoverEffect(panelsalir);
        addMouseHoverEffect(panelpedido);
        
        
//        escritorio.setBackground(new java.awt.Color(0, 153, 204));
//escritorio.setBorder(javax.swing.BorderFactory.createEtchedBorder());


        } 
    
    
    public Frm_Menu(Eusuario ingresar) {
        this.ingresar = ingresar;
        initComponents();
        
       
            
            
        this.setLocationRelativeTo(null);
        
         addMouseHoverEffect(panelcliente);
        addMouseHoverEffect(paneldestajero);
        addMouseHoverEffect(panelmodelo);
        addMouseHoverEffect(panelproducto);
        addMouseHoverEffect(panelusuario);
        addMouseHoverEffect(panelreporte);
        addMouseHoverEffect(panelsalir);
        addMouseHoverEffect(panelpedido);
        
      
        labelusuario.setText(ingresar.getUsuario());
        labelcargo.setText(ingresar.getCargo());
        
  txtcodusuario.setText(String.valueOf(ingresar.getIdUsuario()));
     
        if (ingresar.getCargo().equalsIgnoreCase("Administrador")) {
          
        } else if (ingresar.getCargo().equalsIgnoreCase("Asistente")) {

         panelusuario.setVisible(false);
        
 }
        
    }
    
    

private void ocultarTodosLosFormularios() {
    escritorio.removeAll();
    escritorio.repaint();
}
    

    private void addMouseHoverEffect(JPanel panel) {
        panel.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                panel.setBackground(Color.DARK_GRAY);
            }

            @Override
            public void mouseExited(MouseEvent e) {
                panel.setBackground(Color.BLACK); 
            }
        });
    }
    
    /**

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtcodusuario = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        panelcliente = new javax.swing.JPanel();
        menudestajero = new javax.swing.JLabel();
        paneldestajero = new javax.swing.JPanel();
        menudestajero1 = new javax.swing.JLabel();
        panelmodelo = new javax.swing.JPanel();
        menudestajero2 = new javax.swing.JLabel();
        panelproducto = new javax.swing.JPanel();
        menudestajero3 = new javax.swing.JLabel();
        panelusuario = new javax.swing.JPanel();
        menudestajero6 = new javax.swing.JLabel();
        panelreporte = new javax.swing.JPanel();
        menudestajero5 = new javax.swing.JLabel();
        panelsalir = new javax.swing.JPanel();
        menudestajero7 = new javax.swing.JLabel();
        panelpedido = new javax.swing.JPanel();
        menudestajero4 = new javax.swing.JLabel();
        labelusuario = new javax.swing.JLabel();
        labelcargo = new javax.swing.JLabel();
        escritorio = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setForeground(new java.awt.Color(0, 153, 204));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("_______");

        jLabel1.setBackground(new java.awt.Color(0, 153, 204));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TextilProfitex");

        txtcodusuario.setBackground(new java.awt.Color(0, 153, 204));
        txtcodusuario.setForeground(new java.awt.Color(0, 153, 204));
        txtcodusuario.setText("1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(123, 123, 123)
                        .addComponent(txtcodusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(988, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcodusuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8))
        );

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tipo");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Usuario");

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setForeground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
        );

        panelcliente.setBackground(new java.awt.Color(0, 0, 0));
        panelcliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelclienteMouseClicked(evt);
            }
        });

        menudestajero.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menudestajero.setForeground(new java.awt.Color(255, 255, 255));
        menudestajero.setText("Cliente");

        javax.swing.GroupLayout panelclienteLayout = new javax.swing.GroupLayout(panelcliente);
        panelcliente.setLayout(panelclienteLayout);
        panelclienteLayout.setHorizontalGroup(
            panelclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelclienteLayout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(menudestajero, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        panelclienteLayout.setVerticalGroup(
            panelclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelclienteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(menudestajero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        paneldestajero.setBackground(new java.awt.Color(0, 0, 0));
        paneldestajero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paneldestajeroMouseClicked(evt);
            }
        });

        menudestajero1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menudestajero1.setForeground(new java.awt.Color(255, 255, 255));
        menudestajero1.setText("Destajero");

        javax.swing.GroupLayout paneldestajeroLayout = new javax.swing.GroupLayout(paneldestajero);
        paneldestajero.setLayout(paneldestajeroLayout);
        paneldestajeroLayout.setHorizontalGroup(
            paneldestajeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneldestajeroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(menudestajero1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        paneldestajeroLayout.setVerticalGroup(
            paneldestajeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneldestajeroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(menudestajero1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        panelmodelo.setBackground(new java.awt.Color(0, 0, 0));
        panelmodelo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelmodeloMouseClicked(evt);
            }
        });

        menudestajero2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menudestajero2.setForeground(new java.awt.Color(255, 255, 255));
        menudestajero2.setText("Modelo");

        javax.swing.GroupLayout panelmodeloLayout = new javax.swing.GroupLayout(panelmodelo);
        panelmodelo.setLayout(panelmodeloLayout);
        panelmodeloLayout.setHorizontalGroup(
            panelmodeloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelmodeloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(menudestajero2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        panelmodeloLayout.setVerticalGroup(
            panelmodeloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelmodeloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(menudestajero2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        panelproducto.setBackground(new java.awt.Color(0, 0, 0));
        panelproducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelproductoMouseClicked(evt);
            }
        });

        menudestajero3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menudestajero3.setForeground(new java.awt.Color(255, 255, 255));
        menudestajero3.setText("Producto");

        javax.swing.GroupLayout panelproductoLayout = new javax.swing.GroupLayout(panelproducto);
        panelproducto.setLayout(panelproductoLayout);
        panelproductoLayout.setHorizontalGroup(
            panelproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelproductoLayout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(menudestajero3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        panelproductoLayout.setVerticalGroup(
            panelproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelproductoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(menudestajero3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        panelusuario.setBackground(new java.awt.Color(0, 0, 0));
        panelusuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelusuarioMouseClicked(evt);
            }
        });

        menudestajero6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menudestajero6.setForeground(new java.awt.Color(255, 255, 255));
        menudestajero6.setText("Usuario");

        javax.swing.GroupLayout panelusuarioLayout = new javax.swing.GroupLayout(panelusuario);
        panelusuario.setLayout(panelusuarioLayout);
        panelusuarioLayout.setHorizontalGroup(
            panelusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelusuarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(menudestajero6, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        panelusuarioLayout.setVerticalGroup(
            panelusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelusuarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(menudestajero6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        panelreporte.setBackground(new java.awt.Color(0, 0, 0));
        panelreporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelreporteMouseClicked(evt);
            }
        });

        menudestajero5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menudestajero5.setForeground(new java.awt.Color(255, 255, 255));
        menudestajero5.setText("Reporte");

        javax.swing.GroupLayout panelreporteLayout = new javax.swing.GroupLayout(panelreporte);
        panelreporte.setLayout(panelreporteLayout);
        panelreporteLayout.setHorizontalGroup(
            panelreporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelreporteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(menudestajero5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        panelreporteLayout.setVerticalGroup(
            panelreporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelreporteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(menudestajero5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        panelsalir.setBackground(new java.awt.Color(0, 0, 0));
        panelsalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelsalirMouseClicked(evt);
            }
        });

        menudestajero7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menudestajero7.setForeground(new java.awt.Color(255, 255, 255));
        menudestajero7.setText("Salir");

        javax.swing.GroupLayout panelsalirLayout = new javax.swing.GroupLayout(panelsalir);
        panelsalir.setLayout(panelsalirLayout);
        panelsalirLayout.setHorizontalGroup(
            panelsalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelsalirLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(menudestajero7, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        panelsalirLayout.setVerticalGroup(
            panelsalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelsalirLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(menudestajero7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        panelpedido.setBackground(new java.awt.Color(0, 0, 0));
        panelpedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelpedidoMouseClicked(evt);
            }
        });

        menudestajero4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menudestajero4.setForeground(new java.awt.Color(255, 255, 255));
        menudestajero4.setText("Pedido");

        javax.swing.GroupLayout panelpedidoLayout = new javax.swing.GroupLayout(panelpedido);
        panelpedido.setLayout(panelpedidoLayout);
        panelpedidoLayout.setHorizontalGroup(
            panelpedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelpedidoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(menudestajero4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        panelpedidoLayout.setVerticalGroup(
            panelpedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelpedidoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(menudestajero4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        labelusuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelusuario.setForeground(new java.awt.Color(255, 255, 255));

        labelcargo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelcargo.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelcliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelcargo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(paneldestajero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelproducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelmodelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelpedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelreporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelusuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelsalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(labelusuario))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(labelcargo))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(panelcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(paneldestajero, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelpedido, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(panelreporte, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(panelusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        escritorio.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1106, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 514, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelclienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelclienteMouseClicked

         ocultarTodosLosFormularios();
         
        FrmCliente ventana = new FrmCliente();
escritorio.add(ventana);

ventana.show();

        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_panelclienteMouseClicked

    private void panelproductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelproductoMouseClicked
     ocultarTodosLosFormularios();
        
        FrmProducto ventana = new FrmProducto();
escritorio.add(ventana);

ventana.show();

        // TODO add your handling code here:
    }//GEN-LAST:event_panelproductoMouseClicked

    private void panelsalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelsalirMouseClicked

  this.dispose();
       

        // TODO add your handling code here:
    }//GEN-LAST:event_panelsalirMouseClicked

    private void panelmodeloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelmodeloMouseClicked


     ocultarTodosLosFormularios();

        FrmModelo ventana = new FrmModelo();
escritorio.add(ventana);

ventana.show();



        // TODO add your handling code here:
    }//GEN-LAST:event_panelmodeloMouseClicked

    private void paneldestajeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneldestajeroMouseClicked

     ocultarTodosLosFormularios();
        FrmDestajero ventana = new FrmDestajero();
escritorio.add(ventana);

ventana.show();


        // TODO add your handling code here:
    }//GEN-LAST:event_paneldestajeroMouseClicked

    private void panelpedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelpedidoMouseClicked

     ocultarTodosLosFormularios();
  FrmPedido ventana = new FrmPedido();
escritorio.add(ventana);

ventana.show();





        // TODO add your handling code here:
    }//GEN-LAST:event_panelpedidoMouseClicked

    private void panelreporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelreporteMouseClicked

   ocultarTodosLosFormularios();
  FrmReporteProducto ventana = new FrmReporteProducto();
escritorio.add(ventana);

ventana.show();




        // TODO add your handling code here:
    }//GEN-LAST:event_panelreporteMouseClicked

    private void panelusuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelusuarioMouseClicked

   ocultarTodosLosFormularios();
  FrmUsuario  ventana = new   FrmUsuario();
escritorio.add(ventana);

ventana.show();



        // TODO add your handling code here:
    }//GEN-LAST:event_panelusuarioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel escritorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public static javax.swing.JLabel labelcargo;
    public static javax.swing.JLabel labelusuario;
    private javax.swing.JLabel menudestajero;
    private javax.swing.JLabel menudestajero1;
    private javax.swing.JLabel menudestajero2;
    private javax.swing.JLabel menudestajero3;
    private javax.swing.JLabel menudestajero4;
    private javax.swing.JLabel menudestajero5;
    private javax.swing.JLabel menudestajero6;
    private javax.swing.JLabel menudestajero7;
    private javax.swing.JPanel panelcliente;
    private javax.swing.JPanel paneldestajero;
    private javax.swing.JPanel panelmodelo;
    private javax.swing.JPanel panelpedido;
    private javax.swing.JPanel panelproducto;
    private javax.swing.JPanel panelreporte;
    private javax.swing.JPanel panelsalir;
    private javax.swing.JPanel panelusuario;
    public static javax.swing.JLabel txtcodusuario;
    // End of variables declaration//GEN-END:variables

}
