/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PRESENTACIONES;


import java.awt.Color;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

import ENTIDAD.Epedido;
import NEGOCIO.Npedido;

import javax.swing.table.DefaultTableModel;
//********************************************
import UTILITARIOS.ColorDetallePedido_Jtable;
import javax.swing.table.TableColumnModel;
import UTILITARIOS.Centrar_Datos_Celda_Jtable;
import UTILITARIOS.ColorPedidoEstados;

import javax.swing.table.JTableHeader;
//********************************************

public class FrmConsultaPedido extends javax.swing.JFrame {

         private final Npedido negociopedido= new Npedido();
         
    
         
    public FrmConsultaPedido() {
        initComponents();
             this.setLocationRelativeTo(null);
             
     
  txtcodpedido.setForeground(Color.WHITE);
     
             
        mostrarpedido("");
        
        detalle();
        
           //********************************************   
            JTableHeader  header = cabecerapedido.getTableHeader();
         
    header.setDefaultRenderer(new ColorDetallePedido_Jtable());
    header.setOpaque(false); 
        
    //********************************************
    
     TableColumnModel columnModel = cabecerapedido.getColumnModel();
    for (int i = 0; i < columnModel.getColumnCount(); i++) {
        columnModel.getColumn(i).setCellRenderer(new Centrar_Datos_Celda_Jtable());
    }
    
    //********************************************
    
        
   colorestado();
        
        
    }
private void mostrarpedido(String buscar) {
    DefaultTableModel modelo = new Npedido().mostrar(buscar);
    cabecerapedido.setModel(modelo);
    
   
}



private void colorestado() {
    JTableHeader header = cabecerapedido.getTableHeader();
    header.setOpaque(false);
    TableColumnModel columnModel = cabecerapedido.getColumnModel();
   
    columnModel.getColumn(8).setCellRenderer(new ColorPedidoEstados());
}

private void detalle(){
    
     //********************************************   
            JTableHeader  header = detallepedido.getTableHeader();
         
    header.setDefaultRenderer(new ColorDetallePedido_Jtable());
    header.setOpaque(false); 
        
    //********************************************
    
     TableColumnModel columnModel = detallepedido.getColumnModel();
    for (int i = 0; i < columnModel.getColumnCount(); i++) {
        columnModel.getColumn(i).setCellRenderer(new Centrar_Datos_Celda_Jtable());
    }
    
    //********************************************
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtbuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        cabecerapedido = new javax.swing.JTable();
        btncerrar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        detallepedido = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtcodpedido = new javax.swing.JLabel();
        btnenproceso = new javax.swing.JButton();
        btnentregado = new javax.swing.JButton();
        btnpendiente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Consulta");
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        txtbuscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtbuscar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Consulta de Nombre", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        txtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscarKeyReleased(evt);
            }
        });

        cabecerapedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        cabecerapedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cabecerapedidoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(cabecerapedido);

        btncerrar.setBackground(new java.awt.Color(255, 0, 51));
        btncerrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btncerrar.setForeground(new java.awt.Color(255, 255, 255));
        btncerrar.setText("Cerrar");
        btncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncerrarActionPerformed(evt);
            }
        });

        detallepedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Descripcion", "Cantidad", "Precio", "Importe"
            }
        ));
        detallepedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                detallepedidoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(detallepedido);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Seleccione Nª Pedido para ver su Detalle de Pedido");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Detalle de Pedido");

        btnenproceso.setBackground(new java.awt.Color(102, 102, 102));
        btnenproceso.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnenproceso.setForeground(new java.awt.Color(255, 255, 255));
        btnenproceso.setText("En Proceso");
        btnenproceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnenprocesoActionPerformed(evt);
            }
        });

        btnentregado.setBackground(new java.awt.Color(0, 51, 204));
        btnentregado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnentregado.setForeground(new java.awt.Color(255, 255, 255));
        btnentregado.setText("Entregado");
        btnentregado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnentregadoActionPerformed(evt);
            }
        });

        btnpendiente.setBackground(new java.awt.Color(255, 153, 0));
        btnpendiente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnpendiente.setForeground(new java.awt.Color(255, 255, 255));
        btnpendiente.setText("Pendiente");
        btnpendiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpendienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btncerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnenproceso)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtcodpedido)
                                .addGap(241, 241, 241))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnentregado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnpendiente)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 828, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtbuscar)
                    .addComponent(jScrollPane2))
                .addGap(0, 37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(txtcodpedido))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btncerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnenproceso, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnentregado, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnpendiente, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncerrarActionPerformed

        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_btncerrarActionPerformed

    private void txtbuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyReleased



 String buscar = txtbuscar.getText().trim();
    
  mostrarpedido(buscar);

   colorestado();


        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscarKeyReleased

    private void cabecerapedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cabecerapedidoMouseClicked


         int fila = cabecerapedido.rowAtPoint(evt.getPoint());
       txtcodpedido.setText(cabecerapedido.getValueAt(fila, 0).toString());
         

   int row = cabecerapedido.getSelectedRow();
    if (row != -1) {
        int idPedido = Integer.parseInt(cabecerapedido.getValueAt(row, 0).toString());
        
   
        Npedido f = new Npedido();
        
        
        DefaultTableModel modeloDetallePedido = f.consultarDetallePedido(idPedido);
        
        if (modeloDetallePedido != null) {
         
       detallepedido.setModel(modeloDetallePedido);
            
        } else {
            JOptionPane.showMessageDialog(null, "No se pudo cargar el detalle del pedido.");
        }
    }
        


        // TODO add your handling code here:
    }//GEN-LAST:event_cabecerapedidoMouseClicked

    private void detallepedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_detallepedidoMouseClicked

  







        // TODO add your handling code here:
    }//GEN-LAST:event_detallepedidoMouseClicked

    private void btnenprocesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnenprocesoActionPerformed
      
   String codigoPedido = txtcodpedido.getText();
    if (!codigoPedido.isEmpty()) {
        int idPedido = Integer.parseInt(codigoPedido);
        String nuevoEstado = "EN PROCESO";
        
      
        boolean actualizado = negociopedido.actualizarEstadoPedido(idPedido, nuevoEstado);
        
        if (actualizado) {
            JOptionPane.showMessageDialog(null, "Estado del pedido actualizado a 'EN PROCESO'.");
            mostrarpedido("");
       txtcodpedido.setText("");
                    
   colorestado();
   
        } else {
            JOptionPane.showMessageDialog(null, "Error al actualizar el estado del pedido.");
        }
    } else {
        JOptionPane.showMessageDialog(null, "Seleccione un pedido para actualizar su estado.");
    }
        
    }//GEN-LAST:event_btnenprocesoActionPerformed

    private void btnentregadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnentregadoActionPerformed



    
   String codigoPedido = txtcodpedido.getText();
    if (!codigoPedido.isEmpty()) {
        int idPedido = Integer.parseInt(codigoPedido);
        String nuevoEstado = "ENTREGADO";
        
      
        boolean actualizado = negociopedido.actualizarEstadoPedido(idPedido, nuevoEstado);
        
        if (actualizado) {
            JOptionPane.showMessageDialog(null, "Estado del pedido actualizado a 'ENTREGADO'.");
            mostrarpedido("");
                  txtcodpedido.setText("");
                    
   colorestado();
   
        } else {
            JOptionPane.showMessageDialog(null, "Error al actualizar el estado del pedido.");
        }
    } else {
        JOptionPane.showMessageDialog(null, "Seleccione un pedido para actualizar su estado.");
    }
        





        // TODO add your handling code here:
    }//GEN-LAST:event_btnentregadoActionPerformed

    private void btnpendienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpendienteActionPerformed

 String codigoPedido = txtcodpedido.getText();
    if (!codigoPedido.isEmpty()) {
        int idPedido = Integer.parseInt(codigoPedido);
        String nuevoEstado = "PENDIENTE";
        
      
        boolean actualizado = negociopedido.actualizarEstadoPedido(idPedido, nuevoEstado);
        
        if (actualizado) {
            JOptionPane.showMessageDialog(null, "Estado del pedido actualizado a 'PENDIENTE'.");
            mostrarpedido("");
                  txtcodpedido.setText("");
                    
   colorestado();
   
        } else {
            JOptionPane.showMessageDialog(null, "Error al actualizar el estado del pedido.");
        }
    } else {
        JOptionPane.showMessageDialog(null, "Seleccione un pedido para actualizar su estado.");
    }
        





        // TODO add your handling code here:
    }//GEN-LAST:event_btnpendienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmConsultaPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmConsultaPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmConsultaPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmConsultaPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmConsultaPedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncerrar;
    private javax.swing.JButton btnenproceso;
    private javax.swing.JButton btnentregado;
    private javax.swing.JButton btnpendiente;
    private javax.swing.JTable cabecerapedido;
    private javax.swing.JTable detallepedido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtbuscar;
    private javax.swing.JLabel txtcodpedido;
    // End of variables declaration//GEN-END:variables
}
