/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package PRESENTACIONES;



import BDCONEXION.Conexion;
import java.io.File;
import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;


import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;



import java.awt.Color;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import ENTIDAD.Eproducto;
import NEGOCIO.Nproducto;
import java.util.Calendar;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

import javax.swing.table.JTableHeader;
import UTILITARIOS.ColorDetallePedido_Jtable;
import javax.swing.table.TableColumnModel;
import UTILITARIOS.Centrar_Datos_Celda_Jtable;

import NEGOCIO.Npedido;

import NEGOCIO.NpedidoDetalle;
import ENTIDAD.Epedido;
import ENTIDAD.Epedidodetalle;

import DATO.DAOpedido;
import DATO.DAOpedidodetalle;

import BDCONEXION.Conexion;
import java.sql.Connection;


public class FrmPedido extends javax.swing.JInternalFrame {
  private Conexion mysql = new Conexion();
   private Connection connect = mysql.Conectar();
   
   

   
   
private NEGOCIO.Npedido negocioPedido = new NEGOCIO.Npedido();
 private NpedidoDetalle negocioDetallePedido = new NpedidoDetalle();
       
DefaultTableModel tabla = new DefaultTableModel();


 int filas=0;
      
     
DefaultTableModel model;

      public FrmPedido() {
        initComponents();
        
         getContentPane().setBackground(Color.WHITE);
 
        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null); 

        cboestado.setEnabled(false);
     
        this.setClosable(false);
     
       
        this.setBorder(null);
        
        Calendar cal=Calendar.getInstance();
                                         
java.util.Date date = new java.util.Date();
java.text.SimpleDateFormat sdf=new java.text.SimpleDateFormat("dd/MM/yyyy");


String fecha =sdf.format(date);
 txtfecha.setText(fecha);
             
 
 
   
           JTableHeader header = tbdetalle.getTableHeader();
    header.setDefaultRenderer(new ColorDetallePedido_Jtable());
    header.setOpaque(false); 
        
    
    
     TableColumnModel columnModel = tbdetalle.getColumnModel();
    for (int i = 0; i < columnModel.getColumnCount(); i++) {
        columnModel.getColumn(i).setCellRenderer(new Centrar_Datos_Celda_Jtable());
    }
    
    
      autogenerarNumeroPedido();
      
    }

      
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtpedido = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtcliente = new javax.swing.JTextField();
        txtdestajero = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtruccliente = new javax.swing.JTextField();
        txtrucdestajero = new javax.swing.JTextField();
        cbconsultacliente = new javax.swing.JButton();
        cbconsultadestajero = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtfecha = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtcomentario = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cboestado = new javax.swing.JComboBox<>();
        txtdevolucion = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtcantidad = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtdescripcion = new javax.swing.JTextField();
        btnconsultaproducto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbdetalle = new javax.swing.JTable();
        txttotal = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btnagregar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btncerrar = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btnbuscar = new javax.swing.JButton();
        txtcodcliente = new javax.swing.JLabel();
        txtcoddestajero = new javax.swing.JLabel();
        txtcodproducto = new javax.swing.JLabel();
        txtprecio = new javax.swing.JLabel();
        txtimporte = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        setFocusable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        txtpedido.setEditable(false);
        txtpedido.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Nª Pedido");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtpedido, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtpedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Informacion de Cliente & Destajero"));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Cliente Razon Social");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Destajero Razon Social");

        txtcliente.setEditable(false);

        txtdestajero.setEditable(false);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Ruc");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Ruc");

        txtruccliente.setEditable(false);

        txtrucdestajero.setEditable(false);

        cbconsultacliente.setBackground(new java.awt.Color(204, 204, 0));
        cbconsultacliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbconsultacliente.setForeground(new java.awt.Color(255, 255, 255));
        cbconsultacliente.setText("Consulta");
        cbconsultacliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbconsultaclienteActionPerformed(evt);
            }
        });

        cbconsultadestajero.setBackground(new java.awt.Color(204, 102, 0));
        cbconsultadestajero.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbconsultadestajero.setForeground(new java.awt.Color(255, 255, 255));
        cbconsultadestajero.setText("Consulta");
        cbconsultadestajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbconsultadestajeroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtdestajero, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                    .addComponent(txtcliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtruccliente)
                    .addComponent(txtrucdestajero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbconsultacliente, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .addComponent(cbconsultadestajero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtruccliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbconsultacliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtdestajero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtrucdestajero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbconsultadestajero)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Fechas de Pedidos"));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Fecha");

        txtfecha.setEditable(false);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Comentario");

        jLabel8.setBackground(new java.awt.Color(0, 153, 204));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Fecha Devolucion");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Estado");

        cboestado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PENDIENTE", "EN PROCESO", "CULMINADO", "ENTREGADO", " " }));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Cantidad ");

        txtcantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcantidadActionPerformed(evt);
            }
        });
        txtcantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcantidadKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcantidadKeyTyped(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Descripcion");

        txtdescripcion.setEditable(false);

        btnconsultaproducto.setBackground(new java.awt.Color(0, 153, 153));
        btnconsultaproducto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnconsultaproducto.setForeground(new java.awt.Color(255, 255, 255));
        btnconsultaproducto.setText("Consulta");
        btnconsultaproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultaproductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtcomentario, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                            .addComponent(txtdescripcion))
                        .addGap(13, 13, 13))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                        .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboestado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtdevolucion)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(btnconsultaproducto, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtdevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtcomentario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(cboestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(txtdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnconsultaproducto))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        tbdetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descripcion", "Cantidad", "Precio", "Importe"
            }
        ));
        tbdetalle.setFocusable(false);
        tbdetalle.setSelectionBackground(new java.awt.Color(0, 204, 204));
        tbdetalle.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbdetalle);

        txttotal.setEditable(false);
        txttotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("  Total   S/");

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Pedido de Transacciones"));

        btnagregar.setBackground(new java.awt.Color(0, 51, 153));
        btnagregar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnagregar.setForeground(new java.awt.Color(255, 255, 255));
        btnagregar.setText("Agregar");
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });

        btneliminar.setBackground(new java.awt.Color(255, 51, 0));
        btneliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btneliminar.setForeground(new java.awt.Color(255, 255, 255));
        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        btncerrar.setBackground(new java.awt.Color(255, 153, 0));
        btncerrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btncerrar.setForeground(new java.awt.Color(255, 255, 255));
        btncerrar.setText("Cerrar");
        btncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncerrarActionPerformed(evt);
            }
        });

        btnguardar.setBackground(new java.awt.Color(0, 204, 0));
        btnguardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnguardar.setForeground(new java.awt.Color(255, 255, 255));
        btnguardar.setText("Generar Pedido");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        btnbuscar.setBackground(new java.awt.Color(102, 0, 102));
        btnbuscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnbuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnbuscar.setText("Consultar");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnagregar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnguardar))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnagregar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(btncerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtcodcliente.setForeground(new java.awt.Color(255, 255, 255));
        txtcodcliente.setText("jLabel10");

        txtcoddestajero.setForeground(new java.awt.Color(255, 255, 255));
        txtcoddestajero.setText("jLabel13");

        txtcodproducto.setBackground(new java.awt.Color(255, 255, 255));
        txtcodproducto.setForeground(new java.awt.Color(255, 255, 255));
        txtcodproducto.setText("jLabel");

        txtprecio.setForeground(new java.awt.Color(255, 255, 255));

        txtimporte.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(txtcodproducto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap(203, Short.MAX_VALUE)
                                .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtcodcliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtimporte)
                                .addGap(1, 1, 1)
                                .addComponent(txtcoddestajero)
                                .addGap(248, 248, 248)))
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 841, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtprecio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(122, Short.MAX_VALUE))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcoddestajero)
                    .addComponent(txtcodcliente)
                    .addComponent(txtimporte))
                .addGap(3, 3, 3)
                .addComponent(txtcodproducto)
                .addGap(157, 157, 157)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed

         DefaultTableModel model = (DefaultTableModel) this.tbdetalle.getModel();
    String nuevoCodigo = this.txtcodproducto.getText();
    String cantidadStr = this.txtcantidad.getText();
    boolean productoRepetido = false;

    
    int cantidad;
    try {
        cantidad = Integer.parseInt(cantidadStr);
        if (cantidad <= 0) {
            JOptionPane.showMessageDialog(null, "La cantidad debe ser un número mayor a cero.", "Entrada Inválida", JOptionPane.WARNING_MESSAGE);
            return;
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "La cantidad debe ser un número válido.", "Entrada Inválida", JOptionPane.WARNING_MESSAGE);
        return;
    }

  
    for (int i = 0; i < model.getRowCount(); i++) {
        String codigoExistente = model.getValueAt(i, 0).toString();
        if (nuevoCodigo.equals(codigoExistente)) {
            productoRepetido = true;
            break;
        }
    }

    if (productoRepetido) {
        JOptionPane.showMessageDialog(null, "El producto ya está incluido en el detalle del pedido.", "Detalle del Pedido", JOptionPane.WARNING_MESSAGE);
        return;
    }

    int filaSeleccionada = tbdetalle.getSelectedRow();
    if (filaSeleccionada == -1) {
        model.addRow(new Object[] {
            this.txtcodproducto.getText(),
            this.txtdescripcion.getText(),
            this.txtcantidad.getText(),
            this.txtprecio.getText(),
            this.txtimporte.getText()
        });
    } else {
        model.insertRow(filaSeleccionada + 1, new Object[] {
            this.txtcodproducto.getText(),
            this.txtdescripcion.getText(),
            this.txtcantidad.getText(),
            this.txtprecio.getText(),
            this.txtimporte.getText()
        });
    }

    filas++;
    totales();

    btneliminar.setEnabled(true);
    btnguardar.setEnabled(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnagregarActionPerformed



private void guardarDetallePedido(int idPedido) {
    DefaultTableModel modelo = (DefaultTableModel) tbdetalle.getModel();

    for (int i = 0; i < modelo.getRowCount(); i++) {
        int idProducto = Integer.parseInt(modelo.getValueAt(i, 0).toString());
        String descripcion = modelo.getValueAt(i, 1).toString();
        int cantidad = Integer.parseInt(modelo.getValueAt(i, 2).toString());
        double precio = Double.parseDouble(modelo.getValueAt(i, 3).toString()); 
        double importe = Double.parseDouble(modelo.getValueAt(i, 4).toString()); 

        negocioDetallePedido.insertarDetalle(idPedido, idProducto, descripcion, cantidad, precio, importe);
    }
}



    
  private void autogenerarNumeroPedido() {
    int nuevoIdPedido = negocioPedido.autogenerarNuevoIdPedido();
    txtpedido.setText(String.valueOf(nuevoIdPedido));
}
     
 private void totales() {
    String pre;
    String can;
    double igv = 0;
    double total = 0;
    double subtotal = 0;
    double precio;
    double cantidad;
    double imp = 0.0;

    for (int i = 0; i < tbdetalle.getRowCount(); i++) {
        pre = tbdetalle.getValueAt(i, 2).toString();
        can = tbdetalle.getValueAt(i, 3).toString();

        precio = Double.parseDouble(pre);
        cantidad = Double.parseDouble(can);

        imp = precio * cantidad;

        subtotal += imp;
        igv = subtotal * 0.18;
        total = subtotal + igv;

        tbdetalle.setValueAt(String.format("%.2f", imp), i, 4);
    }

    txttotal.setText(String.format("%.2f", subtotal));
}
    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed

       try  {

            DefaultTableModel modelo = (DefaultTableModel) tbdetalle.getModel();
            int fila = tbdetalle.getSelectedRow();
            if(fila>=0)
            {
                modelo.removeRow(fila);

                totales();

            }
            else
            {
                      JOptionPane.showMessageDialog(null, "Por favor, seleccione un producto en el detalle del pedido para eliminar.", "Detalle del Pedido", JOptionPane.WARNING_MESSAGE);
            }

        }

        catch (Exception e){
        }

    }//GEN-LAST:event_btneliminarActionPerformed

    private void btncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncerrarActionPerformed

        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_btncerrarActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed


 if (Validar()) {
      
            int idPedido = Integer.parseInt(txtpedido.getText());
            int idCliente = Integer.parseInt(txtcodcliente.getText());
            int idEmpresaDestajero = Integer.parseInt(txtcoddestajero.getText());
            String fecha = txtfecha.getText();
            String fechaDevolucion = txtdevolucion.getText();
            double total = Double.parseDouble(txttotal.getText());
            String comentario = txtcomentario.getText();
             int idUsuarioRegistro = Integer.parseInt(Frm_Menu.txtcodusuario.getText());
            String estado = cboestado.getSelectedItem().toString();
            

           
            boolean insertado = negocioPedido.insertarregistro(idPedido,idCliente, idEmpresaDestajero, fecha, fechaDevolucion, total, comentario, idUsuarioRegistro, estado);

          if (insertado) {
            guardarDetallePedido(idPedido);
            limpiar();
            autogenerarNumeroPedido();

            int respuesta = JOptionPane.showConfirmDialog(null, "El Pago ha sido guardado exitosamente. ¿Desea imprimir el pago?", "Confirmación", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

            if (respuesta == JOptionPane.YES_OPTION) {
                
                
                  imprimirPedido();
                
                
                
            } else {
                JOptionPane.showMessageDialog(null, "El pagoo no será impreso.", "Confirmación", JOptionPane.INFORMATION_MESSAGE);
            }
        
  }
  }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnguardarActionPerformed

    
    
        private void imprimirPedido() {
     try {
           
            String urlreporte = "src/main/java/REPORTES/imprimir_pago.jasper";

            
            Map parametros = new HashMap();
            parametros.put("li", txtpedido.getText());

       
            JasperPrint reporte = JasperFillManager.fillReport(urlreporte, parametros, connect);

         
            JasperViewer ventana = new JasperViewer(reporte, false);
            ventana.setTitle("Documento de Pago");
            ventana.setVisible(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al generar el reporte: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        }
       
    private void cbconsultaclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbconsultaclienteActionPerformed




       FrmConsultaCliente x = new      FrmConsultaCliente ();
 
 x.setVisible(true);









        // TODO add your handling code here:
    }//GEN-LAST:event_cbconsultaclienteActionPerformed

    private void cbconsultadestajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbconsultadestajeroActionPerformed


       FrmConsultaDestajero x = new       FrmConsultaDestajero  ();
 
 x.setVisible(true);



        // TODO add your handling code here:
    }//GEN-LAST:event_cbconsultadestajeroActionPerformed

    private void btnconsultaproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultaproductoActionPerformed

     FrmConsultaProducto x = new    FrmConsultaProducto ();
 
 x.setVisible(true);
   txtcantidad.setText("");


        // TODO add your handling code here:
    }//GEN-LAST:event_btnconsultaproductoActionPerformed

    private void txtcantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcantidadActionPerformed

  

        // TODO add your handling code here:
    }//GEN-LAST:event_txtcantidadActionPerformed

    private void txtcantidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcantidadKeyReleased


  String pr = txtprecio.getText().trim();
    String can = txtcantidad.getText().trim(); 

    if (!can.isEmpty() && !pr.isEmpty()) {
        try {
            double n2 = Double.parseDouble(pr);
            double n3 = Double.parseDouble(can);

            double re = n2 * n3;

            txtimporte.setText(String.format("%.2f", re));

            btnagregar.setEnabled(true);
            btneliminar.setEnabled(true);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Por favor, ingresa números válidos para el precio y la cantidad.", "Entrada Inválida", JOptionPane.WARNING_MESSAGE);
        
            txtprecio.setText("");
            txtcantidad.setText("");
            txtimporte.setText("");

            tbdetalle.clearSelection();

            btnagregar.setEnabled(true);
            btneliminar.setEnabled(false);
        }
    }
    

        // TODO add your handling code here:
    }//GEN-LAST:event_txtcantidadKeyReleased

    private void txtcantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcantidadKeyTyped



  try  {

            char c =evt.getKeyChar();

            if(c<'0' || c> '9' ) evt.consume();

        }

        catch (Exception e){
        }





        // TODO add your handling code here:
    }//GEN-LAST:event_txtcantidadKeyTyped

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed

      FrmConsultaPedido x = new       FrmConsultaPedido  ();
 
 x.setVisible(true);


        // TODO add your handling code here:
    }//GEN-LAST:event_btnbuscarActionPerformed
private void actualizarTablaModelos(String buscar) {
    DefaultTableModel modelo = new Nproducto().mostrar(buscar);
    tbdetalle.setModel(modelo);
}

private boolean Validar() {
    if (txtdescripcion.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Por favor seleccione la Descripcion", "Error de Validación", JOptionPane.ERROR_MESSAGE);
        txtdescripcion.requestFocus();
        return false;
    }
    
  
    
    if (txtcantidad.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Por favor ingrese la cantidad .", "Error de Validación", JOptionPane.ERROR_MESSAGE);
        txtcantidad.requestFocus();
        return false;
    }
    
    if (txtcodcliente.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Por favor seleccione el Cliente.", "Error de Validación", JOptionPane.ERROR_MESSAGE);
       
        return false;
    }
    
  
     if (txtcoddestajero.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Por favor seleccione el Destajero.", "Error de Validación", JOptionPane.ERROR_MESSAGE);
       
        return false;
    }
    
  
    
    return true;
}



    private void limpiar() {
        txtdescripcion.setText("");
        txtdescripcion.setText("");
        txtcantidad.setText("");
         txtpedido.setText("");
        txtcodcliente.setText("");
        txtcoddestajero.setText("");
        txtfecha.setText("");
        txtdevolucion.setText("");
        txttotal.setText("");
        txtcomentario.setText("");
        
        txtcliente.setText("");
txtdestajero.setText("");
txtruccliente.setText("");
txtrucdestajero.setText("");
txtprecio.setText("");
txtimporte.setText("");
   

      DefaultTableModel modelo = (DefaultTableModel) tbdetalle.getModel();
        int mover =tbdetalle.getRowCount()-1;
        int i;
        for(i=mover;i>=0;i--)
        {
            modelo.removeRow(i);
        }
 
    }


 
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btncerrar;
    private javax.swing.JButton btnconsultaproducto;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton cbconsultacliente;
    private javax.swing.JButton cbconsultadestajero;
    private javax.swing.JComboBox<String> cboestado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbdetalle;
    public static javax.swing.JTextField txtcantidad;
    public static javax.swing.JTextField txtcliente;
    public static javax.swing.JLabel txtcodcliente;
    public static javax.swing.JLabel txtcoddestajero;
    public static javax.swing.JLabel txtcodproducto;
    private javax.swing.JTextField txtcomentario;
    public static javax.swing.JTextField txtdescripcion;
    public static javax.swing.JTextField txtdestajero;
    private javax.swing.JTextField txtdevolucion;
    private javax.swing.JTextField txtfecha;
    private javax.swing.JLabel txtimporte;
    private javax.swing.JTextField txtpedido;
    public static javax.swing.JLabel txtprecio;
    public static javax.swing.JTextField txtruccliente;
    public static javax.swing.JTextField txtrucdestajero;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
