/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package PRESENTACIONES;

import BDCONEXION.Conexion;
import java.io.File;
import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;

import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import ENTIDAD.Ecliente;
import NEGOCIO.Ncliente;
import javax.swing.table.DefaultTableModel;

//********************************************
import UTILITARIOS.ColorDetallePedido_Jtable;
import javax.swing.table.TableColumnModel;
import UTILITARIOS.Centrar_Datos_Celda_Jtable;
import javax.swing.table.JTableHeader;
//********************************************

public class FrmReporteProducto extends javax.swing.JInternalFrame {

    private Conexion mysql = new Conexion();
    private Connection connect = mysql.Conectar();

    private final Ncliente negocioCliente = new Ncliente();

    public FrmReporteProducto() {
        initComponents();

        getContentPane().setBackground(Color.WHITE);

        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);

        this.setClosable(false);

        this.setBorder(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnreporteproductos = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        setFocusable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnreporteproductos.setBackground(new java.awt.Color(0, 204, 0));
        btnreporteproductos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnreporteproductos.setForeground(new java.awt.Color(255, 255, 255));
        btnreporteproductos.setText("Reporte de Productos");
        btnreporteproductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreporteproductosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(362, 362, 362)
                .addComponent(btnreporteproductos, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(436, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(btnreporteproductos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(241, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnreporteproductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreporteproductosActionPerformed

       Map<String, Object> parametros = new HashMap<>();
	JasperPrint print;

	try {
		JasperReport reporteJasper = JasperCompileManager.compileReport(new File("").
				getAbsolutePath() + "/src/main/java/REPORTES/imprimir_productos.jrxml");
		print = JasperFillManager.fillReport(reporteJasper, parametros, connect);

		JasperViewer visor = new JasperViewer(print, false);
		visor.setTitle("Lista De Entradas");
		visor.setVisible(true);
	} catch (Exception e) {
		e.printStackTrace();
	}


    }//GEN-LAST:event_btnreporteproductosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnreporteproductos;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
